### ISSUE TITLE
[IMPROVE] Raw images in the gallery make cloning the repository super slow

### ISSUE THREAD

**Issue by MesterMan03** [noClaps/ZeroLimits.dev#77]
### Have you read the code of conduct?

- [X] I have read the code of conduct.

### Has this improvement already been suggested?

- [X] My improvement has not been suggested yet.

### Package

gallery

### Where can I improve?

Because of all the raw images found in the gallery's code, cloning the repository takes an extremely long time. It'd be better if the images were hosted outside of GitHub, since they don't have to be on GitHub.

### Anything else?

It also unnecessarily inflates the size on disk.

**Comment by noClaps** [comment]
I could host them on a CDN or something but that would result in me not being able to use the image optimisation from Astro. Also I haven't been able to find any CDNs that provide an easy way for me to import all of my images easily while also optimising them.

Another option would be to use git submodules but that comes with issues of its own, since using submodules is finicky, and I'm not sure how GitHub would feel about me using their service to basically store my own photos. You'd still have to clone the images when cloning the repo.

If you have a solution to either of those, or a different suggestion, then let me know.

**Comment by MesterMan03** [comment]
> I'm not sure how GitHub would feel about me using their service to basically store my own photos
You already do that though.

I think the best option is submodules, they're not that hard to use actually - I'm an active submodule user, and it's pretty simple -, plus they're optional, meaning the user can decide if they want to download the images or not.

**Comment by noClaps** [comment]
Okay I'll give it a try. I suppose it would be pretty nice to have the images be separate from the actual code.

I'll also have to figure out how Vercel handles submodules.
